version: 2
updates:
  - package-ecosystem: pip
    directory: /backend
    schedule:
      interval: weekly
    labels: [dependencies, python]

  - package-ecosystem: npm
    directory: /frontend
    schedule:
      interval: weekly
    labels: [dependencies, javascript]

  - package-ecosystem: npm
    directory: /docs
    schedule:
      interval: weekly
    labels: [dependencies, docs]

  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
    labels: [dependencies, github-actions]
