# SPDX-License-Identifier: AGPL-3.0-only
"""The docs Changelog page must carry the same release notes as CHANGELOG.md.

docs/guide/changelog.md is generated by docs/scripts/sync-changelog.js and
committed, because the published docs are copied from docs/ without running
the docs build. A CHANGELOG.md edit without a regenerated page fails here.
"""

from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parents[2]


def _read(relative: str) -> str:
    return (REPO_ROOT / relative).read_text(encoding="utf-8").replace("\r\n", "\n")


def test_docs_changelog_page_mirrors_changelog() -> None:
    source = _read("CHANGELOG.md")
    assert source.startswith("# Changelog\n")
    body = source.removeprefix("# Changelog\n").lstrip("\n")

    page = _read("docs/guide/changelog.md")

    assert page.startswith("---\ntitle: Changelog\n")
    assert page.endswith(body), (
        "docs/guide/changelog.md is out of date with CHANGELOG.md; run `npm run sync-changelog` in docs/"
    )
