// Shared domain types mirroring the FlowFrame backend REST API.

export interface DatasetSchemaField {
  name: string;
  type: string;
}

export type DatasetSourceType = "csv" | "excel" | "parquet" | "json" | "text";

export interface Project {
  id: string;
  name: string;
  description: string | null;
  /** Brand-palette accent key (e.g. "violet") for the project card. */
  color: string;
  is_default: boolean;
  is_disabled: boolean;
  dataset_count: number;
  flow_count: number;
  created_at: string;
  updated_at: string;
}

export interface ProjectCreate {
  name: string;
  description?: string;
  color?: string;
}

export interface ProjectUpdate {
  name?: string;
  description?: string;
  color?: string;
  is_disabled?: boolean;
}

export interface Dataset {
  id: string;
  name: string;
  source_type: DatasetSourceType;
  /** "input" = uploaded by user; "output" = generated by a flow run. */
  dataset_kind: "input" | "output";
  is_disabled: boolean;
  project_id: string | null;
  /** Highest version number available (latest snapshot). */
  latest_version: number;
  /** Total number of versions uploaded under this name. */
  version_count: number;
  // The backend exposes these under aliased names (column_schema / data_sample);
  // `location` is intentionally never sent to the client. They reflect the latest version.
  column_schema: DatasetSchemaField[] | null;
  data_sample: Record<string, unknown>[] | null;
  column_profile: ColumnProfile[] | null;
  created_at: string;
  updated_at: string;
}

/** Per-column statistics (see backend app/engine/profile.py). Most fields are
 *  type-dependent and only present when relevant to the column's dtype. */
export interface ColumnProfile {
  name: string;
  dtype: "integer" | "float" | "boolean" | "datetime" | "string";
  null_count: number;
  null_pct: number;
  distinct: number;
  scanned: number;
  total: number;
  // numeric
  min?: number | string | null;
  max?: number | string | null;
  mean?: number | null;
  std?: number | null;
  // boolean
  true_count?: number;
  // string
  min_len?: number;
  max_len?: number;
  top_values?: { value: string; count: number }[];
}

export interface DatasetVersion {
  id: string;
  version_number: number;
  row_count: number;
  column_schema: DatasetSchemaField[] | null;
  column_profile: ColumnProfile[] | null;
  source_run_id: string | null;
  created_at: string;
}

/** Dataframe engine a run executes on. Mirrors the backend Engine enum. */
export type Engine = "pandas" | "polars";
export const ENGINES: readonly Engine[] = ["pandas", "polars"];

export type RunStatus = "pending" | "running" | "success" | "failed";

export type NodeResultStatus = "success" | "failed" | "skipped";

export interface NodeResult {
  node_id: string;
  type: string;
  label: string;
  status: NodeResultStatus;
  rows: number | null;
  columns: string[];
  sample: Record<string, unknown>[];
  error: string | null;
  // ML-specific — null for non-ML nodes.
  ml_metrics?: Record<string, number> | null;
  mlflow_run_id?: string | null;
  model_uri?: string | null;
  task_type?: string | null;
  cv_scores?: number[] | null;
  // Assertion node fields — null for non-assertion nodes.
  assertion_passed?: boolean | null;
  assertion_violation_count?: number | null;
  assertion_violating_sample?: Record<string, unknown>[] | null;
}

/** Per-node ML results returned by GET /runs/{id}/ml/metrics. */
export interface MlNodeMetrics {
  node_id: string;
  type: string;
  label: string | null;
  ml_metrics: Record<string, number> | null;
  model_uri: string | null;
  task_type: string | null;
  cv_scores: number[] | null;
  mlflow_run_id: string | null;
}

export interface MlExperiment {
  name: string;
  experiment_id: string;
  lifecycle_stage: string;
  artifact_location: string;
}

export interface MlRegisterResult {
  model_name: string;
  version: string | number;
  model_uri: string;
  alias: string | null;
}

// ---- ML Models page (registry + experiments) ------------------------------

export interface MlLineage {
  flow_id?: string;
  run_id?: string;
  dataset_ids?: string[];
}

export interface MlModelVersion {
  version: string;
  run_id: string | null;
  status: string | null;
  aliases: string[];
  created: string | null;
  metrics: Record<string, number>;
  lineage: MlLineage;
}

export interface MlRegisteredModel {
  name: string;
  description: string | null;
  aliases: Record<string, string>;
  last_updated: string | null;
  versions: MlModelVersion[];
}

export interface MlExperimentSummary {
  experiment_id: string;
  name: string;
  lifecycle_stage: string;
  last_run: string | null;
}

export interface MlExperimentRun {
  run_id: string;
  run_name: string;
  status: string;
  start_time: string | null;
  metrics: Record<string, number>;
  params: Record<string, string>;
  lineage: MlLineage;
}

/** One input dataset a run resolved, with the concrete version it read. */
export interface InputDatasetRef {
  dataset_id: string;
  version_number: number | null;
}

export interface FlowRun {
  id: string;
  flow_id: string;
  input_dataset_id: string | null;
  /** Every input the run resolved (join/concat flows have more than one). */
  input_datasets: InputDatasetRef[] | null;
  status: RunStatus;
  output_location: string | null;
  started_at: string | null;
  finished_at: string | null;
  error_message: string | null;
  logs_json: unknown;
  node_results: NodeResult[] | null;
  /** Resolved flow-parameter values this run executed with (null if none). */
  parameters: ParameterValues | null;
  created_at: string;
}

/** How a run was triggered: a manual click or the background scheduler. */
export type RunTrigger = "manual" | "schedule";

/** Lightweight run row for the history list (no per-node samples). */
export interface FlowRunSummary {
  id: string;
  flow_id: string;
  flow_name: string | null;
  project_id: string | null;
  input_dataset_id: string | null;
  input_datasets: InputDatasetRef[] | null;
  status: RunStatus;
  engine: string;
  trigger: RunTrigger;
  schedule_id: string | null;
  output_location: string | null;
  started_at: string | null;
  finished_at: string | null;
  created_at: string;
}

export interface RunListFilters {
  flow_id?: string;
  project_id?: string;
  dataset_id?: string;
  schedule_id?: string;
  status?: RunStatus;
  started_after?: string;
  started_before?: string;
  sort_by?: string;
  sort_order?: "asc" | "desc";
  limit?: number;
  offset?: number;
}

// ---- Schedules -------------------------------------------------------------

export interface Schedule {
  id: string;
  flow_id: string;
  name: string | null;
  description: string | null;
  cron: string;
  timezone: string;
  /** null = fall back to the server's default engine when the run fires. */
  engine: string | null;
  enabled: boolean;
  catch_up: boolean;
  max_retries: number;
  retry_delay_seconds: number;
  // Runtime / observability state.
  next_run_at: string | null;
  last_fired_at: string | null;
  last_run_id: string | null;
  last_status: RunStatus | null;
  consecutive_failures: number;
  retry_count: number;
  /** Set when the scheduler auto-disabled a chronically failing schedule. */
  disabled_reason: string | null;
  /** Flow-parameter overrides applied to every run this schedule fires. */
  parameters: ParameterValues | null;
  created_at: string;
  updated_at: string;
}

export interface ScheduleCreate {
  cron: string;
  name?: string;
  description?: string;
  timezone?: string;
  engine?: string | null;
  enabled?: boolean;
  catch_up?: boolean;
  max_retries?: number;
  retry_delay_seconds?: number;
  parameters?: ParameterValues | null;
}

export interface ScheduleUpdate {
  cron?: string;
  name?: string;
  description?: string;
  timezone?: string;
  engine?: string | null;
  enabled?: boolean;
  catch_up?: boolean;
  max_retries?: number;
  retry_delay_seconds?: number;
  parameters?: ParameterValues | null;
}

// ---- Flow parameters -------------------------------------------------------

/** Declared type of a flow parameter (mirrors the backend ParameterType enum). */
export type ParameterType = "string" | "integer" | "number" | "boolean";
export const PARAMETER_TYPES: readonly ParameterType[] = [
  "string",
  "integer",
  "number",
  "boolean",
];

/** A parameter declared on a flow, stored in graph_json.parameters. Node configs
 *  reference it via `{{ name }}`; values resolve at run/preview/schedule time. */
export interface ParameterSpec {
  name: string;
  type: ParameterType;
  /** Default value (already typed). Absent/null means the parameter is required. */
  default?: unknown;
  description?: string | null;
}

/** Resolved or override parameter values keyed by name. */
export type ParameterValues = Record<string, unknown>;

// React Flow compatible graph stored in flow.graph_json.
export interface GraphNodeData {
  label: string;
  config: Record<string, unknown>;
  [key: string]: unknown;
}

export interface GraphNode {
  id: string;
  type: string;
  position: { x: number; y: number };
  data: GraphNodeData;
}

export interface GraphEdge {
  id: string;
  source: string;
  target: string;
  sourceHandle?: string | null;
  targetHandle?: string | null;
}

export interface GraphJson {
  nodes: GraphNode[];
  edges: GraphEdge[];
  /** Engine persisted with the graph so the editor restores the last choice. */
  engine?: "pandas" | "polars";
  /** Parameters declared on the flow (referenced by node configs via {{ name }}). */
  parameters?: ParameterSpec[];
}

export interface Flow {
  id: string;
  name: string;
  description: string | null;
  project_id: string | null;
  graph_json: GraphJson | null;
  is_disabled: boolean;
  created_at: string;
  updated_at: string;
  /** When this flow last ran (any trigger), or null if it never has. */
  last_run_at: string | null;
}

export interface FlowCreate {
  name: string;
  description?: string;
  project_id?: string;
  graph_json: GraphJson;
}

export interface FlowUpdate {
  name?: string;
  description?: string;
  project_id?: string;
  graph_json?: GraphJson;
  is_disabled?: boolean;
}

// ---- Connections (database sources/sinks) ---------------------------------

export interface Connection {
  id: string;
  name: string;
  provider: string;
  /** Derived from provider: "sql" | "mongo" | "storage" */
  connection_type: string;
  host: string | null;
  port: number | null;
  database: string | null;
  username: string | null;
  /** NAME of an env var holding the password — never the secret itself. */
  password_env: string | null;
  options: Record<string, unknown> | null;
  created_at: string;
  updated_at: string;
  /** When the connection was last tested (any test, pass or fail). */
  last_tested_at: string | null;
}

export interface ConnectionCreate {
  name: string;
  provider: string;
  host?: string | null;
  port?: number | null;
  database?: string | null;
  username?: string | null;
  password_env?: string | null;
  options?: Record<string, unknown> | null;
}

export type ConnectionUpdate = Partial<ConnectionCreate>;

export interface ProviderInfo {
  name: string;
  label: string;
  kind: "sql" | "mongo" | "storage" | "mlflow";
  available: boolean;
  driver_module: string | null;
  extra: string | null;
  default_port: number | null;
  needs_host: boolean;
  needs_auth: boolean;
  supports_query: boolean;
  needs_bucket: boolean;
  needs_region: boolean;
  needs_endpoint: boolean;
}

export interface ConnectionTestResult {
  ok: boolean;
  message: string;
}

export interface TableInfo {
  name: string;
  schema_name: string | null;
  qualified: string;
}

export interface PreviewResponse {
  columns: string[];
  rows: Record<string, unknown>[];
  row_count: number;
  truncated: boolean;
  profile: ColumnProfile[] | null;
}

export interface FlowPreviewRequest {
  node_id?: string;
  limit?: number;
  profile?: boolean;
  /** Flow-parameter overrides so the preview reflects the values a run would use. */
  parameters?: ParameterValues | null;
}

export interface TransformationPreviewRequest {
  type: string;
  dataset_id: string;
  config: Record<string, unknown>;
  limit?: number;
  profile?: boolean;
}

/** Portable, environment-independent description of a flow (name + node graph). */
export interface FlowDocument {
  format: string;
  name: string;
  description?: string | null;
  graph_json: Record<string, unknown>;
}

/** Import payload: only the graph is required; the rest is optional metadata. */
export interface FlowImport {
  format?: string;
  name?: string;
  description?: string | null;
  project_id?: string;
  graph_json: Record<string, unknown>;
}

export interface ExportCodeResponse {
  /** pandas script (kept as `code` for back-compat). */
  code: string;
  /** eager polars equivalent. */
  polars: string;
  /** optimized lazy polars (`scan_*` → `collect()`) equivalent. */
  polars_lazy: string;
  /** importable JSON description of the flow. */
  flow_document: FlowDocument;
}
