// Shared domain types mirroring the Ciaren backend REST API.

export interface DatasetSchemaField {
  name: string;
  type: string;
}

export type DatasetSourceType = "csv" | "tsv" | "excel" | "parquet" | "json" | "jsonl" | "text";

export interface Project {
  id: string;
  name: string;
  description: string | null;
  /** Brand-palette accent key (e.g. "violet") for the project card. */
  color: string;
  is_default: boolean;
  is_disabled: boolean;
  dataset_count: number;
  flow_count: number;
  created_at: string;
  updated_at: string;
}

export interface ProjectCreate {
  name: string;
  description?: string;
  color?: string;
}

export interface ProjectUpdate {
  name?: string;
  description?: string;
  color?: string;
  is_disabled?: boolean;
}

export interface Dataset {
  id: string;
  name: string;
  source_type: DatasetSourceType;
  /** "input" = uploaded by user; "output" = generated by a flow run. */
  dataset_kind: "input" | "output";
  is_disabled: boolean;
  project_id: string | null;
  /** Highest version number available (latest snapshot). */
  latest_version: number;
  /** Total number of versions uploaded under this name. */
  version_count: number;
  // The backend exposes these under aliased names (column_schema / data_sample);
  // `location` is intentionally never sent to the client. They reflect the latest version.
  column_schema: DatasetSchemaField[] | null;
  data_sample: Record<string, unknown>[] | null;
  column_profile: ColumnProfile[] | null;
  /** The ORIGINAL upload's dialect (delimiter/encoding/decimal/sheet) when it
   *  wasn't the default; the stored copy is normalized at ingest. Optional so
   *  test fixtures predating the field stay valid. */
  parse_options?: Record<string, string | number> | null;
  created_at: string;
  updated_at: string;
}

/** Optional dialect overrides for an upload; omitted fields are auto-detected. */
export interface UploadParseOptions {
  delimiter?: string;
  encoding?: string;
  decimal?: string;
  sheet?: string;
}

/** Per-column statistics (see backend app/engine/profile.py). Most fields are
 *  type-dependent and only present when relevant to the column's dtype. */
export interface ColumnProfile {
  name: string;
  dtype: "integer" | "float" | "boolean" | "datetime" | "string";
  null_count: number;
  null_pct: number;
  distinct: number;
  scanned: number;
  total: number;
  // numeric
  min?: number | string | null;
  max?: number | string | null;
  mean?: number | null;
  std?: number | null;
  // boolean
  true_count?: number;
  // string
  min_len?: number;
  max_len?: number;
  top_values?: { value: string; count: number }[];
}

export interface DatasetVersion {
  id: string;
  version_number: number;
  row_count: number;
  column_schema: DatasetSchemaField[] | null;
  column_profile: ColumnProfile[] | null;
  source_run_id: string | null;
  created_at: string;
}

/** Dataframe engine a run executes on. Mirrors the backend Engine enum. */
export type Engine = "pandas" | "polars";
export const ENGINES: readonly Engine[] = ["pandas", "polars"];

export type RunStatus = "pending" | "running" | "success" | "failed" | "cancelled";

export type NodeResultStatus = "success" | "failed" | "skipped";

export interface NodeResult {
  node_id: string;
  type: string;
  label: string;
  status: NodeResultStatus;
  rows: number | null;
  columns: string[];
  sample: Record<string, unknown>[];
  error: string | null;
  // ML-specific — null for non-ML nodes.
  ml_metrics?: Record<string, number> | null;
  mlflow_run_id?: string | null;
  model_uri?: string | null;
  task_type?: string | null;
  cv_scores?: number[] | null;
  // Assertion node fields — null for non-assertion nodes.
  assertion_passed?: boolean | null;
  assertion_violation_count?: number | null;
  assertion_violating_sample?: Record<string, unknown>[] | null;
  // Chart node artifact — null for non-chart nodes.
  chart?: ChartArtifact | null;
}

// ---- Chart-node artifacts (stored on the run by the backend chart nodes) ----

export interface ChartCategoryDatum {
  label: string;
  value: number | null;
}

export interface BoxGroupStats {
  label: string;
  min: number;
  q1: number;
  median: number;
  q3: number;
  max: number;
  outliers: number;
  count: number;
}

/** Render-ready chart data computed by a chart node over the full run data.
 *  Shapes mirror backend/app/engine/transformations/charts.py. */
export interface ChartArtifact {
  kind: "bar" | "line" | "area" | "scatter" | "pie" | "histogram" | "boxplot" | "heatmap";
  rows_seen?: number;
  /** Optional user-set chart title (falls back to the node label). */
  title?: string;
  // bar / pie / histogram
  data?: ChartCategoryDatum[];
  x?: string;
  y?: string | null;
  aggregate?: string;
  orientation?: "vertical" | "horizontal";
  category?: string;
  value?: string | null;
  column?: string;
  bins?: number;
  total_categories?: number;
  // stacked bar / line / area
  rows?: Array<Record<string, string | number | null>>;
  series?: string[];
  group_by?: string | null;
  total_series?: number;
  total_points?: number;
  // scatter
  points?: Array<[number | null, number | null]>;
  // boxplot
  groups?: BoxGroupStats[];
  total_groups?: number;
  // heatmap
  columns?: string[];
  matrix?: Array<Array<number | null>>;
  total_columns?: number;
  /** Explicitly chosen heatmap columns that weren't numeric/varying enough. */
  dropped_columns?: string[];
}

/** Per-node ML results returned by GET /runs/{id}/ml/metrics. */
export interface MlNodeMetrics {
  node_id: string;
  type: string;
  label: string | null;
  ml_metrics: Record<string, number> | null;
  model_uri: string | null;
  task_type: string | null;
  cv_scores: number[] | null;
  mlflow_run_id: string | null;
}

export interface MlExperiment {
  name: string;
  experiment_id: string;
  lifecycle_stage: string;
  artifact_location: string;
}

export interface MlRegisterResult {
  model_name: string;
  version: string | number;
  model_uri: string;
  alias: string | null;
}

// ---- ML Models page (registry + experiments) ------------------------------

export interface MlLineage {
  flow_id?: string;
  run_id?: string;
  dataset_ids?: string[];
}

export interface MlModelVersion {
  version: string;
  run_id: string | null;
  status: string | null;
  aliases: string[];
  created: string | null;
  metrics: Record<string, number>;
  lineage: MlLineage;
}

export interface MlRegisteredModel {
  name: string;
  description: string | null;
  aliases: Record<string, string>;
  last_updated: string | null;
  versions: MlModelVersion[];
}

export interface MlModelCatalogItem {
  model_type: string;
  task: string;
  available: boolean;
  requires: string[];
  missing: string[];
  warning: string | null;
  /** Contributing provider: "ciaren.ml" for built-ins, a plugin id otherwise. */
  provider?: string;
  /** Display label (plugin model types only; built-ins are mirrored statically). */
  label?: string | null;
  supervised?: boolean;
  default_hyperparameters?: Record<string, unknown>;
  hyperparameter_schema?: ConfigSchema;
}

export interface MlExperimentSummary {
  experiment_id: string;
  name: string;
  lifecycle_stage: string;
  last_run: string | null;
}

export interface MlExperimentRun {
  run_id: string;
  run_name: string;
  status: string;
  start_time: string | null;
  metrics: Record<string, number>;
  params: Record<string, string>;
  lineage: MlLineage;
}

/** One input dataset a run resolved, with the concrete version it read. */
export interface InputDatasetRef {
  dataset_id: string;
  version_number: number | null;
}

export interface FlowRun {
  id: string;
  flow_id: string;
  input_dataset_id: string | null;
  /** Every input the run resolved (join/concat flows have more than one). */
  input_datasets: InputDatasetRef[] | null;
  status: RunStatus;
  output_location: string | null;
  started_at: string | null;
  finished_at: string | null;
  error_message: string | null;
  logs_json: unknown;
  node_results: NodeResult[] | null;
  /** Resolved flow-parameter values this run executed with (null if none). */
  parameters: ParameterValues | null;
  created_at: string;
}

/** How a run was triggered: a manual click or the background scheduler. */
export type RunTrigger = "manual" | "schedule";

/** Lightweight run row for the history list (no per-node samples). */
export interface FlowRunSummary {
  id: string;
  flow_id: string;
  flow_name: string | null;
  project_id: string | null;
  input_dataset_id: string | null;
  input_datasets: InputDatasetRef[] | null;
  status: RunStatus;
  engine: string;
  trigger: RunTrigger;
  schedule_id: string | null;
  output_location: string | null;
  started_at: string | null;
  finished_at: string | null;
  created_at: string;
}

export interface RunListFilters {
  flow_id?: string;
  project_id?: string;
  dataset_id?: string;
  schedule_id?: string;
  status?: RunStatus;
  started_after?: string;
  started_before?: string;
  sort_by?: string;
  sort_order?: "asc" | "desc";
  limit?: number;
  offset?: number;
}

// ---- Schedules -------------------------------------------------------------

/** A minimal run reference for the recent-run history strip on the schedules list. */
export interface ScheduleRunBrief {
  id: string;
  status: RunStatus;
  created_at: string;
}

export interface Schedule {
  id: string;
  flow_id: string;
  name: string | null;
  description: string | null;
  cron: string;
  timezone: string;
  /** null = fall back to the server's default engine when the run fires. */
  engine: string | null;
  is_enabled: boolean;
  catch_up: boolean;
  max_retries: number;
  retry_delay_seconds: number;
  // Runtime / observability state.
  next_run_at: string | null;
  last_fired_at: string | null;
  last_run_id: string | null;
  last_status: RunStatus | null;
  consecutive_failures: number;
  retry_count: number;
  /** Set when the scheduler auto-disabled a chronically failing schedule. */
  disabled_reason: string | null;
  /** Most recent runs this schedule fired (newest first). Absent from responses
   * served by a backend older than the field, so treat as optional at runtime. */
  recent_runs?: ScheduleRunBrief[];
  /** Flow-parameter overrides applied to every run this schedule fires. */
  parameters: ParameterValues | null;
  created_at: string;
  updated_at: string;
}

export interface ScheduleCreate {
  cron: string;
  name?: string;
  description?: string;
  timezone?: string;
  engine?: string | null;
  is_enabled?: boolean;
  catch_up?: boolean;
  max_retries?: number;
  retry_delay_seconds?: number;
  parameters?: ParameterValues | null;
}

export interface ScheduleUpdate {
  cron?: string;
  name?: string;
  description?: string;
  timezone?: string;
  engine?: string | null;
  is_enabled?: boolean;
  catch_up?: boolean;
  max_retries?: number;
  retry_delay_seconds?: number;
  parameters?: ParameterValues | null;
}

// ---- Flow parameters -------------------------------------------------------

/** Declared type of a flow parameter (mirrors the backend ParameterType enum). */
export type ParameterType = "string" | "integer" | "number" | "boolean";
export const PARAMETER_TYPES: readonly ParameterType[] = [
  "string",
  "integer",
  "number",
  "boolean",
];

/** A parameter declared on a flow, stored in graph_json.parameters. Node configs
 *  reference it via `{{ name }}`; values resolve at run/preview/schedule time. */
export interface ParameterSpec {
  name: string;
  type: ParameterType;
  /** Default value (already typed). Absent/null means the parameter is required. */
  default?: unknown;
  description?: string | null;
}

/** Resolved or override parameter values keyed by name. */
export type ParameterValues = Record<string, unknown>;

// React Flow compatible graph stored in flow.graph_json.
export interface GraphNodeData {
  label: string;
  config: Record<string, unknown>;
  [key: string]: unknown;
}

export interface GraphNode {
  id: string;
  type: string;
  position: { x: number; y: number };
  data: GraphNodeData;
}

export interface GraphEdge {
  id: string;
  source: string;
  target: string;
  sourceHandle?: string | null;
  targetHandle?: string | null;
}

export interface GraphJson {
  nodes: GraphNode[];
  edges: GraphEdge[];
  /** Engine persisted with the graph so the editor restores the last choice. */
  engine?: "pandas" | "polars";
  /** Parameters declared on the flow (referenced by node configs via {{ name }}). */
  parameters?: ParameterSpec[];
}

export interface Flow {
  id: string;
  name: string;
  description: string | null;
  project_id: string | null;
  graph_json: GraphJson | null;
  is_disabled: boolean;
  created_at: string;
  updated_at: string;
  /** When this flow last ran (any trigger), or null if it never has. */
  last_run_at: string | null;
}

export interface FlowCreate {
  name: string;
  description?: string;
  project_id?: string;
  graph_json: GraphJson;
}

export interface FlowUpdate {
  name?: string;
  description?: string;
  project_id?: string;
  graph_json?: GraphJson;
  is_disabled?: boolean;
}

// ---- Connections (database sources/sinks) ---------------------------------

export interface Connection {
  id: string;
  name: string;
  provider: string;
  /** Derived from provider: "sql" | "mongo" | "storage" */
  connection_type: string;
  host: string | null;
  port: number | null;
  database: string | null;
  username: string | null;
  /** NAME of an env var holding the password — never the secret itself. */
  password_env: string | null;
  options: Record<string, unknown> | null;
  created_at: string;
  updated_at: string;
  /** When the connection was last tested (any test, pass or fail). */
  last_tested_at: string | null;
}

export interface ConnectionCreate {
  name: string;
  provider: string;
  host?: string | null;
  port?: number | null;
  database?: string | null;
  username?: string | null;
  password_env?: string | null;
  options?: Record<string, unknown> | null;
}

export type ConnectionUpdate = Partial<ConnectionCreate>;

/** One field of a schema-driven config form (mirrors app/plugin_api ConfigFieldSpec). */
export interface ConfigField {
  key: string;
  label?: string;
  type?:
    | "string"
    | "number"
    | "integer"
    | "boolean"
    | "select"
    | "string_list"
    | "column"
    | "column_list";
  required?: boolean;
  default?: unknown;
  placeholder?: string;
  help?: string;
  options?: string[];
  min?: number | null;
  max?: number | null;
  secret?: boolean;
}

export interface ConfigSchema {
  fields?: ConfigField[];
}

export interface ProviderInfo {
  name: string;
  label: string;
  /** Core kinds are closed; a plugin connector may declare its own (e.g. "api"). */
  kind: "sql" | "mongo" | "storage" | "mlflow" | (string & {});
  available: boolean;
  driver_module: string | null;
  extra: string | null;
  default_port: number | null;
  needs_host: boolean;
  needs_auth: boolean;
  supports_query: boolean;
  needs_bucket: boolean;
  needs_region: boolean;
  needs_endpoint: boolean;
  /** Present (true) only for plugin-contributed connectors. */
  plugin?: boolean;
  plugin_id?: string;
  /** Extra connector-specific form fields, stored in the connection's options. */
  config_schema?: ConfigSchema;
}

export interface ConnectionTestResult {
  ok: boolean;
  message: string;
}

export interface TableInfo {
  name: string;
  schema_name: string | null;
  qualified: string;
}

/** Whether this host has a usable OS keychain (headless servers don't). */
export interface KeyringAvailability {
  available: boolean;
  backend: string | null;
  detail: string | null;
}

/** A keychain entry's presence and its `keyring:NAME` reference — never its value. */
export interface KeyringSecretStatus {
  name: string;
  exists: boolean;
  reference: string;
}

export interface KeyringSecretWrite {
  name: string;
  value: string;
  overwrite?: boolean;
}

export interface PreviewResponse {
  columns: string[];
  rows: Record<string, unknown>[];
  row_count: number;
  truncated: boolean;
  profile: ColumnProfile[] | null;
}

export interface FlowPreviewRequest {
  node_id?: string;
  limit?: number;
  profile?: boolean;
  /** Flow-parameter overrides so the preview reflects the values a run would use. */
  parameters?: ParameterValues | null;
}

export interface TransformationPreviewRequest {
  type: string;
  dataset_id: string;
  config: Record<string, unknown>;
  limit?: number;
  profile?: boolean;
}

/** Portable, environment-independent description of a flow (name + node graph). */
export interface FlowDocument {
  format: string;
  name: string;
  description?: string | null;
  graph_json: Record<string, unknown>;
}

/** Import payload: accepts either envelope — the legacy `graph_json` shape
 * (today's real export format) or the versioned `graph`/`schemaVersion`
 * shape — at least one of `graph_json`/`graph` is required. */
export interface FlowImport {
  format?: string;
  name?: string;
  description?: string | null;
  project_id?: string;
  graph_json?: Record<string, unknown>;
  graph?: Record<string, unknown>;
  schemaVersion?: string;
}

/** Response from the standalone, non-persisting flow-document migration
 * utility (`POST /flows/migrate-document`). */
export interface FlowMigrateDocumentResponse {
  document: Record<string, unknown>;
  migrated: boolean;
  from_version: string;
  to_version: string;
}

export interface ExportCodeResponse {
  /** pandas script (kept as `code` for back-compat). */
  code: string;
  /** eager polars equivalent. */
  polars: string;
  /** optimized lazy polars (`scan_*` → `collect()`) equivalent. */
  polars_lazy: string;
  /** importable JSON description of the flow. */
  flow_document: FlowDocument;
}

// ---- Catalog (backend-fed node metadata) -----------------------------------
// Mirrors app/plugin_api NodeSpec/PortSpec, served by GET /api/catalog/nodes.

export type CatalogPortKind = "dataframe" | "model";

export interface CatalogPort {
  id: string;
  type: CatalogPortKind;
  required: boolean;
  multi: boolean;
}

export interface CatalogNode {
  id: string;
  label: string;
  category: string;
  description: string;
  provider: string;
  version: string;
  inputs: CatalogPort[];
  outputs: CatalogPort[];
  default_config: Record<string, unknown>;
  capabilities: string[];
  permissions: string[];
  requires_ml: boolean;
  is_model_sink: boolean;
  is_flow_terminal?: boolean;
  config_schema: ConfigSchema;
}

// ---- Plugins ---------------------------------------------------------------

export type PluginStatus = "loaded" | "disabled" | "needs_permissions" | "needs_license";

export interface PluginInfo {
  id: string;
  name: string;
  version: string;
  publisher: string;
  description: string;
  source: string;
  status: PluginStatus;
  /** Human-readable context for a gated status (e.g. why the license is invalid). */
  status_detail: string;
  capabilities: string[];
  /** Permissions the plugin requests. */
  permissions: string[];
  /** Permissions the user has granted it. */
  granted_permissions: string[];
  /** Requested-but-not-yet-granted permissions (non-empty ⇒ needs approval). */
  missing_permissions: string[];
  /** How the package verified at install time: trusted | untrusted | unsigned | invalid | "". */
  signature: string;
  /** First-party: verified as trusted under a publisher key pinned into the app
   *  itself (not merely a user-added trusted key). Derived, never declared. */
  official: boolean;
  /** Node type ids this plugin contributes to the editor palette. */
  nodes: string[];
  /** Palette category/subgroup for each contributed node. */
  node_categories: Record<string, string>;
  /** Connector ids this plugin contributes (loaded plugins only). */
  connectors?: string[];
  /** Trainable model-type ids this plugin contributes to the ML catalog. */
  model_types?: string[];
  /** True when the plugin lives in the managed install dir and can be uninstalled
   *  via DELETE. False for dev-dir / entry-point plugins (disable-only). */
  uninstallable: boolean;
  /** Manifest license kind: community | commercial | "" (no manifest). */
  license: string;
  /** Declared marketplace trust tier: trusted | verified | community | "". */
  trust: string;
  /** PEP 440 specifier of compatible Ciaren versions (e.g. ">=0.1"). */
  ciaren_spec: string;
  /** pip requirements the plugin declares it needs. */
  dependencies: string[];
  /** Dotted entry point (module.path:ClassName) from the manifest. */
  entrypoint: string;
  /** Managed install directory on disk, "" when the plugin lives elsewhere. */
  install_path: string;
}

export interface LicenseStatus {
  plugin_id: string;
  valid: boolean;
  license_type: string | null;
  expires_at: string | null;
  reason: string | null;
}

export interface PluginErrorInfo {
  source: string;
  error: string;
}

export interface PluginDiagnostics {
  loaded: PluginInfo[];
  gated: PluginInfo[];
  errors: PluginErrorInfo[];
}

export interface PluginInstallResult {
  plugin: PluginInfo;
  /** Signature trust outcome: trusted | untrusted | unsigned | invalid. */
  outcome: string;
  reason: string;
}

export interface PluginUninstallResult {
  plugin_id: string;
  /** True if managed install files were deleted; false if there was nothing to
   *  remove (dev-dir / entry-point plugin) — its persisted state is still cleared. */
  removed: boolean;
}

export interface MarketplaceEntry {
  id: string;
  name: string;
  version: string;
  publisher: string;
  description: string;
  license: string;
  /** Derived by verifying the local artifact's signature:
   *  "official" (first-party pinned key) | "trusted" | "community". */
  trust: string;
  capabilities: string[];
  permissions: string[];
  /** PEP 440 specifier of compatible Ciaren versions ("" for older indexes). */
  ciaren_spec: string;
  /** pip requirements the plugin declares it needs (advisory). */
  dependencies: string[];
  /** Node type ids this catalog entry contributes after install + approval. */
  nodes: string[];
  /** Palette category/subgroup for each contributed node. */
  node_categories: Record<string, string>;
  license_required: boolean;
  /** A plugin with this id is already installed. */
  installed: boolean;
  /** The installed plugin's version ("" when not installed or unknown). */
  installed_version: string;
  /** The catalog offers a strictly newer version than the installed one. */
  update_available: boolean;
  /** The catalog has withdrawn this plugin (installing is refused). */
  revoked: boolean;
  /** The artifact is available locally for one-click install. */
  installable: boolean;
}

export interface MarketplaceCatalog {
  /** False when no index is configured (the UI explains how to enable it). */
  configured: boolean;
  plugins: MarketplaceEntry[];
  /** Installed plugin ids the catalog has revoked (may already be delisted). */
  revoked_installed: string[];
}

// ---- App settings (runtime-editable server configuration) ------------------

export type AppSettingSource = "default" | "env" | "override";

export interface AppSetting {
  key: string;
  label: string;
  description: string;
  /** The CIAREN_* env var this setting maps to; ignored while an override exists. */
  env_var: string;
  category: string;
  value_type: "integer" | "select" | "url";
  choices: string[] | null;
  min_value: number | null;
  max_value: number | null;
  /** The value is read once at startup; a change needs a server restart. */
  restart_required: boolean;
  /** Effective value and where it comes from (override beats env beats default). */
  value: number | string;
  source: AppSettingSource;
  default_value: number | string;
  /** What "Reset" falls back to: the env var if set, else the default. */
  env_value: number | string;
}
